# Generated by Django 5.1.15 on 2026-08-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SETTLEMENT_RETURNED', '보완요청'), ('SETTLEMENT_REJECTED', '반려'), ('TEAM_COLLECT_PENDING', '팀 취합 대기'), ('REVIEW_PENDING', '회계 검토 대기'), ('DOC_INGEST_DONE', '규정 문서 처리 완료'), ('DOC_INGEST_FAILED', '규정 문서 처리 실패'), ('RULE_AUTO_CREATED', '규정에서 룰 자동 생성'), ('RULE_UPDATED', '룰 생성·수정 완료'), ('RULE_SIMULATION_DONE', '룰 검증 보고서'), ('RULE_ACTIVATION_REQUESTED', '룰 활성화 요청'), ('RULE_ACTIVATED', '활성 룰 변경')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(max_length=300)),
                ('target', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('count', models.PositiveIntegerField(default=1)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='ix_notif_recipient_read')],
            },
        ),
    ]
