# Generated by Django 5.1.15 on 2026-07-24 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('PERSONAL', '개인 배정'), ('TEAM', '팀 카드'), ('SHARED', '공용'), ('POST_PAID', '후정산'), ('PREPAID', '선결제·충전형')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('number_masked', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='accounts.team')),
            ],
        ),
    ]
