# Generated by Django 5.1.15 on 2026-08-21 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='limit_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='월 한도(원)'),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '정상'), ('STOPPED', '정지·회수')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='card',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='stopped_reason',
            field=models.TextField(blank=True, verbose_name='정지 사유'),
        ),
    ]
