# Generated by Django 5.1.15 on 2026-07-24 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('업무활성', '업무활성'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], max_length=20)),
                ('ai_category', models.CharField(blank=True, choices=[('업무활성', '업무활성'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], max_length=20)),
                ('ai_suggested', models.BooleanField(default=False)),
                ('merchant_industry', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('SUBMITTED', '제출됨'), ('RPA_JUDGED', '1차판정'), ('PENDING_CONFIRM', '승인대기'), ('RETURNED', '보완요청'), ('IN_REVIEW', '검토중'), ('REJECT', '반려(최종)'), ('CONFIRMED', '확정'), ('ERP_VOUCHER_DRAFTED', '전표생성')], default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='accounts.team')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='settlements.settlement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
