# Generated by Django 5.1.15 on 2026-07-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='purpose',
            field=models.CharField(blank=True, max_length=300, verbose_name='지출 목적/사유'),
        ),
    ]
