# Generated by Django 5.1.15 on 2026-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_settlement_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('DRAFT', '개인 보유중'), ('TEAM_COLLECTING', '팀 취합중'), ('TEAM_RETURNED', '팀 보완요청'), ('TEAM_REJECTED', '팀 반려'), ('SUBMITTED', '회계 제출'), ('RPA_JUDGED', '1차판정'), ('PENDING_CONFIRM', '승인대기'), ('RETURNED', '보완요청'), ('IN_REVIEW', '검토중'), ('REJECT', '반려(최종)'), ('CONFIRMED', '확정'), ('ERP_VOUCHER_DRAFTED', '전표생성')], default='DRAFT', max_length=24),
        ),
    ]
