# Generated by Django 5.1.15 on 2026-07-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('settlements', '0003_alter_settlement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='YYYY-MM')),
                ('category', models.CharField(blank=True, choices=[('업무활성', '업무활성'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], max_length=20)),
                ('limit_amount', models.PositiveBigIntegerField(default=0, verbose_name='한도(원)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.team')),
            ],
            options={
                'ordering': ['team', 'year_month', 'category'],
                'unique_together': {('team', 'year_month', 'category')},
            },
        ),
    ]
