# Generated by Django 5.1.15 on 2026-08-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0005_alter_settlement_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='actual_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_settlements', to=settings.AUTH_USER_MODEL, verbose_name='카드 실사용자'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='actual_user_recorded',
            field=models.BooleanField(blank=True, help_text='공용·팀 카드에서만 의미 있다. 개인카드는 조립기가 True로 채운다.', null=True, verbose_name='실사용자 기록 여부'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='external_headcount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='외부 참석 인원'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='headcount',
            field=models.PositiveIntegerField(blank=True, help_text="0 = 참석자 기록 없음(=명단 누락). 비우면 '모름'.", null=True, verbose_name='참석 인원'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='includes_alcohol',
            field=models.BooleanField(blank=True, null=True, verbose_name='주류 포함'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='is_secondary_venue',
            field=models.BooleanField(blank=True, null=True, verbose_name='2차 성격 지출'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='item_type',
            field=models.CharField(blank=True, choices=[('식사', '식사·다과'), ('선물', '선물'), ('경조사', '경조사비'), ('상품권', '상품권·유가증권'), ('행사성', '행사성'), ('숙박', '숙박'), ('교통', '교통'), ('소모품', '소모품·비품'), ('기타', '기타')], help_text='청탁금지 한도(kickback_limit_table) 룩업 키로도 쓰인다.', max_length=20, verbose_name='지출 세부유형'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='kickback_target',
            field=models.BooleanField(blank=True, null=True, verbose_name='청탁금지법 대상자 참석'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='pre_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='사전승인 받음'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIPT', '영수증·카드전표'), ('PRE_APPROVAL', '사전승인 문서(결재)'), ('MEETING_MINUTES', '회의록'), ('PARTICIPANT_LIST', '참석자 명단'), ('TRIP_PLAN', '출장계획서'), ('CONTRACT', '계약서·견적서'), ('OTHER', '기타')], default='OTHER', max_length=20)),
                ('file_ref', models.CharField(blank=True, max_length=300, verbose_name='파일 경로/키')),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', '추출 대기'), ('RUNNING', '추출 중'), ('DONE', '추출 완료'), ('FAILED', '추출 실패'), ('SKIPPED', '추출 대상 아님')], default='PENDING', max_length=10)),
                ('extracted', models.JSONField(blank=True, default=dict, verbose_name='추출 사실(dot-path→값)')),
                ('field_confidence', models.JSONField(blank=True, default=dict, verbose_name='경로별 신뢰도')),
                ('evidence_spans', models.JSONField(blank=True, default=list, verbose_name='추출 근거 위치')),
                ('extractor_version', models.CharField(blank=True, max_length=32)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='settlements.settlement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['settlement_id', 'kind', 'id'],
                'indexes': [models.Index(fields=['settlement', 'kind'], name='ix_attachment_settle_kind')],
            },
        ),
    ]
