# Generated by Django 5.1.15 on 2026-08-14 02:52
"""Category.OPERATION("업무활성") 폐지 → Category.GATHERING("회식") 신설(같은 enum 슬롯 재사용).

⚠️ 데이터 이관은 '업무활성'→'회식' 문자열 치환이 **아니다**. '업무활성'은 실제로는 미분류
캐치올(가맹점 키워드 못 맞춘 기본값 + 우체국·택배·인쇄 등 일반 업무비, `draft_agent.py` 참조)이었고
'회식'(팀 회식·회식비 규정)과는 무관한 다른 개념이다 — 그래서 기존 '업무활성' 데이터는 '비품'
(SUPPLIES)으로 보낸다. 이건 코드 쪽(`draft_agent.py`의 캐치올 기본값·`seed.py`의 기존
C.OPERATION 시드 항목)에서 내린 것과 같은 결정이다.
"""
from django.db import migrations, models


def operation_to_supplies(apps, schema_editor):
    Settlement = apps.get_model('settlements', 'Settlement')
    TeamBudget = apps.get_model('settlements', 'TeamBudget')
    Settlement.objects.filter(category='업무활성').update(category='비품')
    Settlement.objects.filter(ai_category='업무활성').update(ai_category='비품')
    # TeamBudget은 (team, year_month, category) 유니크라 '업무활성'→'비품' UPDATE가 이미 존재하는
    # '비품' 행과 충돌한다(팀마다 6개 과목 전부 예산 행을 만드는 seed.py 관례상 거의 항상 존재).
    # 이 표는 seed.py가 매번 실 지출 합계에서 역산해 새로 만드는 순수 파생 데이터라(과거 이력이
    # 아님) 병합 대신 삭제한다 — 다음 `seed --fresh`가 '회식' 포함 6개 과목으로 다시 채운다.
    TeamBudget.objects.filter(category='업무활성').delete()


def supplies_to_operation(apps, schema_editor):
    # 역방향은 원본 복원이 불가능하다('업무활성'이던 행과 원래 '비품'이던 행이 구분 안 됨,
    # TeamBudget은 삭제돼 애초에 복원할 행이 없음) — 명시적으로 no-op으로 둔다(자동 되돌리기
    # 시 데이터를 조용히 더 틀리게 만들지 않기 위함).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0006_settlement_actual_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], max_length=20),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='category',
            field=models.CharField(blank=True, choices=[('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teambudget',
            name='category',
            field=models.CharField(blank=True, choices=[('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], max_length=20),
        ),
        migrations.RunPython(operation_to_supplies, supplies_to_operation),
    ]
