# Generated by Django 5.1.15 on 2026-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0007_alter_settlement_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='rule_judged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='룰 판정 시각'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='rule_judgement',
            field=models.JSONField(blank=True, default=dict, verbose_name='룰 판정 결과'),
        ),
    ]
