# Generated by Django 5.1.15 on 2026-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0008_settlement_rule_judged_at_settlement_rule_judgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='merchant_industry_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
