# Generated by Django 5.1.15 on 2026-08-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0010_canonicalize_settlement_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='attachments/%Y%m/', verbose_name='원본 파일'),
        ),
    ]
