# Generated by Django 5.1.15 on 2026-08-21 06:36

from django.db import migrations, models


def backfill_state(apps, schema_editor):
    """이미 결과가 있는 건은 `DONE`으로 표시한다.

    기본값(`NOT_STARTED`)은 "검토 대상이 아니다(룰 통과)"라는 뜻이라, 그대로 두면
    **이미 검토를 마친 과거 건이 화면에서 「룰 판정으로 통과된 건」으로 표시**된다.
    """
    Settlement = apps.get_model("settlements", "Settlement")
    Settlement.objects.filter(risk_reviews__isnull=False).distinct().update(risk_review_state="DONE")


def noop(apps, schema_editor):
    """되돌리기는 아무것도 하지 않는다 — 컬럼 자체가 사라지므로 값을 복원할 곳이 없다."""


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0011_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='risk_review_error',
            field=models.TextField(blank=True, verbose_name='Risk Review 실패 사유'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='risk_review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='risk_review_state',
            field=models.CharField(
                choices=[('NOT_STARTED', '미실시'), ('RUNNING', '검토 중'),
                         ('DONE', '완료'), ('FAILED', '실패')],
                default='NOT_STARTED', max_length=12, verbose_name='Risk Review 상태',
            ),
        ),
        migrations.RunPython(backfill_state, noop),
    ]
