# Generated by Django 5.1.15 on 2026-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0012_settlement_risk_review_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품'), ('기타', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='category',
            field=models.CharField(blank=True, choices=[('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품'), ('기타', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teambudget',
            name='category',
            field=models.CharField(blank=True, choices=[('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품'), ('기타', '기타')], max_length=20),
        ),
    ]
