"""체크박스 서식 증빙 2종 추가 — 회식 실시 확인서·접대 확인서.

선택지를 **넓히는** 변경이라 안전하다(좁히는 쪽이 위험하다 — ).
기존 행은 이 값을 쓰지 않는다.
"""
# Generated by Django 5.1.15 on 2026-08-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0016_alter_settlement_ai_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('RECEIPT', '영수증·카드전표'), ('PRE_APPROVAL', '사전승인 문서(결재)'), ('MEETING_MINUTES', '회의록'), ('PARTICIPANT_LIST', '참석자 명단'), ('TRIP_PLAN', '출장계획서'), ('DINING_REPORT', '회식 실시 확인서'), ('HOSPITALITY_REPORT', '접대 확인서'), ('CONTRACT', '계약서·견적서'), ('OTHER', '기타')], default='OTHER', max_length=20),
        ),
    ]
