# Generated by Django 5.1.15 on 2026-07-24 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('APPROVE', '승인'), ('RETURN', '보완요청'), ('REJECT', '반려'), ('CORRECT', '수정')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_labels', to='settlements.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('rag_refs', models.JSONField(blank=True, default=list)),
                ('ai_recommendation', models.CharField(blank=True, max_length=10)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('review_prob', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_reviews', to='settlements.settlement')),
            ],
            options={
                'ordering': ['-anomaly_score'],
            },
        ),
    ]
