# Generated by Django 5.1.15 on 2026-07-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='anomaly_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
