# Generated by Django 5.1.15 on 2026-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_riskreview_anomaly_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='rag_report',
            field=models.TextField(blank=True),
        ),
    ]
