# Generated by Django 5.1.15 on 2026-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_riskreview_rag_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='stage2_verdict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
