# Generated by Django 5.1.15 on 2026-08-21 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_riskreview_stage2_verdict'),
        ('settlements', '0012_settlement_risk_review_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='비용분류')),
                ('outcome', models.CharField(max_length=10)),
                ('diverged_from', models.CharField(choices=[('AI', 'AI 권고와 다름'), ('RULE', '룰 판정과 다름')], max_length=8)),
                ('expected', models.CharField(blank=True, max_length=16, verbose_name='AI 권고 또는 룰 판정')),
                ('ai_recommendation', models.CharField(blank=True, max_length=10)),
                ('rule_decision', models.CharField(blank=True, max_length=10)),
                ('rule_flags', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField()),
                ('text', models.TextField()),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('citation', models.CharField(blank=True, max_length=100, verbose_name='표시용 출처')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Chroma 적재 시각')),
                ('index_error', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, help_text='정산이 지워져도 사례는 남는다 — 이미 임베딩돼 검색에 쓰이고 있다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_cases', to='settlements.settlement')),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['indexed_at'], name='ix_decisioncase_indexed')],
            },
        ),
    ]
