# Generated by Django 5.1.15 on 2026-08-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_riskreview_stage2_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='risk_tier',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
