# Generated by Django 5.1.15 on 2026-08-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_riskreview_risk_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskreview',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
