# Generated by Django 5.1.15 on 2026-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_decisioncase'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='stage1_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='stage1_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
