# Generated by Django 5.1.15 on 2026-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_riskreview_stage1_note_riskreview_stage1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='model_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='tier_path',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
