# Generated by Django 5.1.15 on 2026-07-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('limit_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('required_evidence', models.JSONField(blank=True, default=list)),
                ('tax_note', models.TextField(blank=True)),
                ('refs', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('file_ref', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scope', models.CharField(default='GLOBAL', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('SIMULATED', '시뮬레이션'), ('ACTIVE', '활성'), ('ARCHIVED', '보관')], default='DRAFT', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('entry_node_key', models.CharField(blank=True, max_length=64)),
                ('sim_result', models.JSONField(blank=True, default=dict)),
                ('source_clause', models.CharField(blank=True, max_length=200)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_graphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_version', models.PositiveIntegerField(default=0)),
                ('path', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(blank=True, max_length=12)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.rulegraph')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_hits', to='settlements.settlement')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='RuleRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node_key', models.CharField(max_length=64)),
                ('on_result', models.CharField(choices=[('MATCH', '일치'), ('NO_MATCH', '불일치'), ('PASS', '통과'), ('REJECT', '반려'), ('REVIEW', '검토')], max_length=10)),
                ('to_node_key', models.CharField(blank=True, max_length=64)),
                ('priority', models.IntegerField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='policies.rulegraph')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='RuleGraphVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policies.rulegraph')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('graph', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RuleNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=64)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('action', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='policies.rulegraph')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('graph', 'node_key')},
            },
        ),
    ]
