# Generated by Django 5.1.15 on 2026-08-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_rulegraph_version_constraints'),
        ('settlements', '0005_alter_settlement_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegraph',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulegraph',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rulegraph',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_graphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RuleSimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('period_label', models.CharField(blank=True, max_length=40)),
                ('structure_error', models.CharField(blank=True, max_length=300)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('grades', models.JSONField(blank=True, default=dict)),
                ('agent_report', models.TextField(blank=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='policies.rulegraph')),
                ('ran_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RuleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('merchant_type', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('expected', models.CharField(blank=True, max_length=12)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='policies.rulegraph')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('graph', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RuleSimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TEST', '검증셋'), ('HISTORY', '실제 내역')], max_length=8)),
                ('row_key', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('date_label', models.CharField(blank=True, max_length=16)),
                ('current_status', models.CharField(blank=True, max_length=24)),
                ('baseline', models.CharField(blank=True, max_length=12)),
                ('decision', models.CharField(blank=True, max_length=12)),
                ('path', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('expected', models.CharField(blank=True, max_length=12)),
                ('matched_expectation', models.BooleanField(blank=True, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('risk', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('ai_comment', models.TextField(blank=True)),
                ('comment_verdict', models.CharField(blank=True, max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='settlements.settlement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='policies.rulesimulationrun')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='policies.ruletestcase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
