# Generated by Django 5.1.15 on 2026-08-03 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_rulegraph_review_comment_rulegraph_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAuthoringMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(choices=[('user', '사용자'), ('ai', 'Rule Agent')], max_length=8)),
                ('text', models.TextField()),
                ('applied_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='policies.rulegraph')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
