# Generated by Django 5.1.15 on 2026-08-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_ruleauthoringmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulenode',
            name='condition_text',
            field=models.TextField(blank=True),
        ),
    ]
