# Generated by Django 5.1.15 on 2026-08-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_rulenode_condition_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('key_axes', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_clause', models.CharField(blank=True, max_length=200)),
                ('effective_date', models.DateField()),
                ('superseded_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='policies.policydoc')),
            ],
            options={
                'ordering': ['key', '-effective_date'],
            },
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.AddIndex(
            model_name='policytable',
            index=models.Index(fields=['key', 'effective_date'], name='ix_policy_table_lookup'),
        ),
        migrations.AddConstraint(
            model_name='policytable',
            constraint=models.UniqueConstraint(fields=('key', 'effective_date'), name='uq_policy_table_key_effective'),
        ),
    ]
