# Generated by Django 5.1.15 on 2026-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_policytable_delete_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytable',
            name='strict_keys',
            field=models.BooleanField(default=False, help_text="False(기본): 축 값을 몰라도 '*' 기본값으로 해소한다 — 회사 기본 한도처럼 기본값이 의미 있는 표.\nTrue: 축 값을 모르면 해소하지 않고 null로 남긴다 — 금지업종처럼 '모르면 안전하다'고 단정할 수 없는 표. null이면 미해소 가드가 REVIEW로 강등한다.", verbose_name='키 미상 시 해소 금지'),
        ),
    ]
