# Generated by Django 5.1.15 on 2026-08-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_policytable_strict_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegraph',
            name='generation_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
