# Generated by Django 5.1.15 on 2026-08-14 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_rulegraph_generation_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policydoc',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='policydoc',
            name='file_ref',
        ),
        migrations.AddField(
            model_name='policydoc',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='collection',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='doc_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='file',
            field=models.FileField(blank=True, upload_to='policy_docs/%Y%m/', verbose_name='원본 파일'),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='leaf_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='profile',
            field=models.CharField(blank=True, max_length=16, verbose_name='문서 유형'),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='rule_scope',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='rule_trigger',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('PARSING', '파싱·청킹 중'), ('INDEXING', '임베딩·적재 중'), ('DONE', '적재 완료'), ('FAILED', '실패')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_policy_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
