# Generated by Django 5.1.15 on 2026-08-14 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_rulegraph_scope_data_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulegraph',
            name='ck_rulegraph_scope',
        ),
        migrations.AlterField(
            model_name='rulegraph',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', '공통 필수 게이트'), ('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품')], default='GLOBAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rulegraph',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['GLOBAL', 'TEST_DEMO', '회식', '회의', '식대', '출장', '접대', '비품'])), name='ck_rulegraph_scope'),
        ),
    ]
