# Generated by Django 5.1.15 on 2026-08-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_remove_rulegraph_ck_rulegraph_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policydoc',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='원본 크기(byte)'),
        ),
        migrations.AddField(
            model_name='policydoc',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='policies.policydoc'),
        ),
        migrations.CreateModel(
            name='PolicyFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='policies.policyfolder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='policydoc',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='policies.policyfolder'),
        ),
        migrations.CreateModel(
            name='PolicyClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article_no', models.PositiveIntegerField(blank=True, null=True)),
                ('article_label', models.CharField(blank=True, max_length=32, verbose_name='조 라벨')),
                ('article_title', models.CharField(blank=True, max_length=200)),
                ('citation', models.CharField(blank=True, db_index=True, max_length=300)),
                ('body', models.TextField(blank=True, verbose_name='원문(Markdown)')),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('chunk_ids', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(blank=True, choices=[('', '미결정'), ('SKIP', '규칙 생성 안 함')], default='', max_length=8)),
                ('decision_reason', models.TextField(blank=True, verbose_name='결정 사유')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_clauses', to=settings.AUTH_USER_MODEL)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='policies.policydoc')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('doc', 'article_label'), name='uq_clause_doc_article')],
            },
        ),
        migrations.AddConstraint(
            model_name='policyfolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uq_policyfolder_parent_name'),
        ),
    ]
