# Generated by Django 5.1.15 on 2026-08-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_policydoc_file_size_policydoc_superseded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydoc',
            name='profile_hint',
            field=models.CharField(blank=True, choices=[('REGULATION', '사내 규정'), ('LAW', '법령·시행령'), ('DIAGRAM', '조직도·도해'), ('GENERIC', '기타 문서')], max_length=16, verbose_name='문서 유형(지정)'),
        ),
        migrations.AlterField(
            model_name='policydoc',
            name='profile',
            field=models.CharField(blank=True, choices=[('REGULATION', '사내 규정'), ('LAW', '법령·시행령'), ('DIAGRAM', '조직도·도해'), ('GENERIC', '기타 문서')], max_length=16, verbose_name='문서 유형(판정)'),
        ),
    ]
