# Generated by Django 5.1.15 on 2026-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0015_policydoc_profile_hint_alter_policydoc_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesimulationrun',
            name='agent_report_placeholder',
            field=models.BooleanField(default=True),
        ),
    ]
