# Generated by Django 5.1.15 on 2026-08-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0015_policydoc_profile_hint_alter_policydoc_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='코드')),
                ('label', models.CharField(max_length=60, verbose_name='표기')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='분류')),
                ('severity', models.CharField(blank=True, max_length=10, verbose_name='심각도')),
                ('owner', models.CharField(blank=True, max_length=20, verbose_name='해소 주체')),
                ('is_system', models.BooleanField(default=False, verbose_name='시스템 플래그')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '판정 플래그',
                'verbose_name_plural': '판정 플래그',
                'ordering': ['category', 'code'],
            },
        ),
    ]
