# Generated by Django 5.1.15 on 2026-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_rulesimulationrun_agent_report_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesimulationresult',
            name='ai_comment_detail',
            field=models.TextField(blank=True),
        ),
    ]
