# Generated by Django 5.1.15 on 2026-08-19 03:37

from django.db import migrations


class Migration(migrations.Migration):
    """두 갈래로 갈린 `0016_*`을 합친다(작업 없음).

    main의 `0016_ruleflag`(네임드 플래그 레지스트리)와 rule-agent-v1의
    `0016_rulesimulationrun_agent_report_placeholder`→`0017_*`(시뮬레이션 보고서 필드)이
    같은 부모(`0015_*`)에서 각자 뻗어 나와 리프가 둘이 됐다. **번호를 새로 매기지 않고
    합치는 이유**: 이미 각 브랜치 로컬 DB에 적용된 이름이라, 이름을 바꾸면 그쪽 
    `django_migrations` 기록과 어긋나 재적용을 시도하게 된다.
    """

    dependencies = [
        ('policies', '0016_ruleflag'),
        ('policies', '0017_rulesimulationresult_ai_comment_detail'),
    ]

    operations = [
    ]
