# Generated by Django 5.1.15 on 2026-08-22 11:28

from django.conf import settings
from django.db import migrations, models

#  `Category.OTHER("기타")` 추가에 따른 scope 제약 **넓히기**.
#  0009~0011("업무활성"→"회식")에서 제약을 최종 상태로 한 번에 바꿨다가 구값 행 때문에
#  `AddConstraint`가 IntegrityError로 죽어 3단계(넓히기→이관→좁히기)로 쪼갰던 이력이 있다.
#  이번은 **집합이 커지기만** 하므로(기존 값 전부 유효) 그 분리가 필요 없다 — 값을 빼거나
#  이름을 바꾸는 변경이면 그때는 다시 3단계로 가야 한다.


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_merge_20260819_1237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rulegraph',
            name='ck_rulegraph_scope',
        ),
        migrations.AlterField(
            model_name='rulegraph',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', '공통 필수 게이트'), ('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('비품', '비품'), ('기타', '기타')], default='GLOBAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rulegraph',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['GLOBAL', 'TEST_DEMO', '회식', '회의', '식대', '출장', '접대', '비품', '기타'])), name='ck_rulegraph_scope'),
        ),
    ]
