# Generated by Django 5.1.15 on 2026-08-22 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_merge_20260819_1237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policyclause',
            name='triage_kind',
            field=models.CharField(blank=True, choices=[('', '미분류'), ('RULE', '규정 조항'), ('INFO', '안내·설명'), ('ANNEX', '별표 참조')], default='', max_length=8, verbose_name='AI 분류'),
        ),
        migrations.AddField(
            model_name='policyclause',
            name='triage_priority',
            field=models.CharField(blank=True, choices=[('', '미지정'), ('AUTO', '자동 생성'), ('P1', '1순위'), ('P2', '2순위'), ('P3', '3순위'), ('SKIP', '제외')], default='', max_length=8, verbose_name='룰 생성 우선순위'),
        ),
        migrations.AddField(
            model_name='policyclause',
            name='triage_reason',
            field=models.TextField(blank=True, verbose_name='분류 근거'),
        ),
        migrations.AddField(
            model_name='policyclause',
            name='triage_summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='규칙 요약'),
        ),
        migrations.AddField(
            model_name='policyclause',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PolicyTableProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_chunk_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_label', models.CharField(blank=True, max_length=100, verbose_name='별표 표기')),
                ('citation', models.CharField(blank=True, max_length=300)),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('raw_markdown', models.TextField(blank=True, verbose_name='표 원문')),
                ('key', models.CharField(blank=True, max_length=64, verbose_name='별표 key')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('key_axes', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('strict_keys', models.BooleanField(default=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, verbose_name='AI 메모')),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인됨'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('review_note', models.TextField(blank=True, verbose_name='검토 메모')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='policies.policytable')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_proposals', to='policies.policydoc')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_table_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '별표 후보',
                'verbose_name_plural': '별표 후보',
                'ordering': ['doc_id', 'source_label', 'id'],
            },
        ),
    ]
