# Generated by Django 5.1.15 on 2026-08-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0019_policyclause_triage_kind_and_more'),
        ('policies', '0019_remove_rulegraph_ck_rulegraph_scope_and_more'),
    ]

    operations = [
    ]
