# Generated by Django 5.1.15 on 2026-08-24 05:41

from django.conf import settings
from django.db import migrations, models

#  `Category`에서 "비품"을 뺀 데 따른 scope 제약 **좁히기**(2026-08-24).
#
#  좁히는 방향이라 **옛 값을 쓰는 행이 남아 있으면 `AddConstraint`가 죽는다** —
#  0009~0011("업무활성"→"회식")에서 실제로 겪어 넓히기→이관→좁히기 3단계로 쪼갰던 그 자리다.
#  그래서 ① 정산·예산 이관은 `settlements/0015`가 먼저 하고(아래 dependencies) ② 룰 그래프
#  scope 이관은 이 파일이 제약을 다시 걸기 **전에** 한다.

RETIRED_SCOPE = "비품"
REPLACEMENT_SCOPE = "기타"


def move_supplies_graphs(apps, schema_editor):
    """`비품` scope 그래프를 `기타`로 옮긴다.

    제품이 심는 그래프에는 없지만(GLOBAL·접대·회식·출장·TEST_DEMO), 룰 콘솔에서 사람이
    만들었을 수 있다. 있는데 그냥 제약을 걸면 마이그레이션이 통째로 실패한다.
    **삭제하지 않고 옮기는 이유**: 사람이 만든 룰을 마이그레이션이 조용히 지우면 안 된다.
    """
    RuleGraph = apps.get_model("policies", "RuleGraph")
    RuleGraph.objects.filter(scope=RETIRED_SCOPE).update(scope=REPLACEMENT_SCOPE)


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0020_merge_20260822_2255'),
        #  **이관이 먼저다**(위 주석). 정산·팀예산의 "비품"을 옮긴 뒤에야 제약을 좁힐 수 있다.
        ('settlements', '0015_retire_supplies_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(move_supplies_graphs, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='rulegraph',
            name='ck_rulegraph_scope',
        ),
        migrations.AlterField(
            model_name='rulegraph',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', '공통 필수 게이트'), ('회식', '회식'), ('회의', '회의'), ('식대', '식대'), ('출장', '출장'), ('접대', '접대'), ('기타', '기타')], default='GLOBAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rulegraph',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['GLOBAL', 'TEST_DEMO', '회식', '회의', '식대', '출장', '접대', '기타'])), name='ck_rulegraph_scope'),
        ),
    ]
