"""별표 후보에 AI 코멘트·활용 안내·자동검사 결과와 「생성 안 함」 상태를 더한다.

전부 신규 컬럼이고 기존 행은 기본값(빈 문자열·빈 목록)으로 남는다 — 예전 제안은
코멘트가 없을 뿐 승인 흐름은 그대로 돈다.

`status`에 `SKIPPED`가 늘어난다. **넓히는 변경이라 안전하다**(좁히는 쪽이 위험하다 —
`settlements/0015`에서 겪었다). 기존 행은 이 값을 쓰지 않는다.
"""
# Generated by Django 5.1.15 on 2026-08-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0021_remove_rulegraph_ck_rulegraph_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytableproposal',
            name='checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policytableproposal',
            name='comment',
            field=models.TextField(blank=True, verbose_name='AI 코멘트'),
        ),
        migrations.AddField(
            model_name='policytableproposal',
            name='skip_reason',
            field=models.TextField(blank=True, verbose_name='생성 안 함 사유'),
        ),
        migrations.AddField(
            model_name='policytableproposal',
            name='usage_note',
            field=models.TextField(blank=True, verbose_name='활용 안내'),
        ),
        migrations.AlterField(
            model_name='policytableproposal',
            name='status',
            field=models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인됨'), ('REJECTED', '반려'), ('SKIPPED', '생성 안 함')], default='PENDING', max_length=10),
        ),
    ]
