# Generated by Django 5.1.15 on 2026-07-24 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('place_id', models.CharField(blank=True, max_length=64)),
                ('industry_code', models.CharField(blank=True, max_length=32)),
                ('industry_label', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('CACHE', '캐시'), ('KAKAO', '카카오 지도'), ('WEB', '웹검색')], default='CACHE', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'merchant categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ts', models.DateTimeField(verbose_name='거래일시')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.card')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ref', models.CharField(blank=True, max_length=300)),
                ('ocr_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('UPLOADED', '업로드됨'), ('MATCHED', '매칭됨'), ('MISSING', '누락')], default='UPLOADED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='transactions.transaction')),
            ],
        ),
    ]
