# Generated by Django 5.1.15 on 2026-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantcategory',
            name='industry_code',
            field=models.CharField(blank=True, choices=[('RESTAURANT', '일반음식점'), ('CAFE', '카페'), ('BAR_ENTERTAINMENT', '주점/유흥'), ('KARAOKE', '노래연습장'), ('GAMBLING', '사행성업종'), ('LODGING', '숙박'), ('GOLF', '골프장'), ('LEISURE', '레저'), ('MART', '마트/편의점'), ('DUTY_FREE', '면세점'), ('PERSONAL_CARE', '이·미용'), ('OFFICE_SUPPLIES', '문구/사무용품'), ('FUEL_TRANSPORT', '주유/교통'), ('ELECTRONICS', '전자/가전'), ('OTHER', '기타')], max_length=32),
        ),
        migrations.AlterField(
            model_name='merchantcategory',
            name='source',
            field=models.CharField(choices=[('CACHE', '캐시'), ('KAKAO', '카카오 지도')], default='CACHE', max_length=10),
        ),
    ]
