# Generated by Django 5.1.15 on 2026-07-24 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', '전표(안)'), ('CONFIRMED', '확정')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='settlements.settlement')),
            ],
        ),
    ]
