# Generated by Django 5.1.15 on 2026-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', '사용자(임직원)'), ('TEAM_LEAD', '팀장(제출 단위)'), ('ACCOUNTANT', '회계 담당자'), ('ACCOUNTANT_LEAD', '회계팀장'), ('EXECUTIVE', '회계·운영 상부')], default='EMPLOYEE', max_length=20),
        ),
    ]
