# Generated by Django 5.1.15 on 2026-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
