# Generated by Django 5.1.15 on 2026-08-18 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_extra_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='코드')),
                ('name', models.CharField(help_text='별표 룩업 키로 그대로 쓰인다.', max_length=32, unique=True, verbose_name='표기')),
                ('rank', models.PositiveSmallIntegerField(help_text='클수록 상위. 결재선 비교에 쓴다.', verbose_name='서열')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
            ],
            options={
                'verbose_name': '직책',
                'verbose_name_plural': '직책',
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='코드')),
                ('name', models.CharField(help_text='별표 룩업 키로 그대로 쓰인다.', max_length=32, unique=True, verbose_name='표기')),
                ('rank', models.PositiveSmallIntegerField(help_text='클수록 상위. 결재선 비교에 쓴다.', verbose_name='서열')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
            ],
            options={
                'verbose_name': '직급',
                'verbose_name_plural': '직급',
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.jobtitle', verbose_name='직책'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.position', verbose_name='직급'),
        ),
    ]
