# Generated by Django 5.1.15 on 2026-08-19 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobtitle_position_user_job_title_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='assignable_titles',
            field=models.JSONField(blank=True, default=list, verbose_name='보임 가능 직책'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(blank=True, help_text='결재권·카드한도의 기준. 규정상 발령일부터 적용된다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.jobtitle', verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, help_text='급여·승진 등 처우 기준(표시용). 한도·결재권 판정에는 쓰이지 않는다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.position', verbose_name='직급'),
        ),
    ]
